version: "3.2"

services:
 # Database to put tracking/stats/etc.
  trackdb:
    image: solr:8.4-slim
    user: "8983:8983"
    ports:
     - "8983:8983"
    environment:
     - "SOLR_HEAP=2g"
    volumes:
      - ${DATA_TRACKDB}:/var/solr
    entrypoint:
#      - docker-entrypoint.sh
      - solr-precreate
      - tracking
