
version: '3.7'

services:
  solrcloud:
    image: solr:8.11
    #command: solr -f -cloud
    environment:
     - "SOLR_HEAP=2g"
     - "JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true"
    entrypoint:
      - bash
      - "-c"
      - "init-var-solr; exec solr -f -cloud"
    user: "${CURRENT_UID}"
    volumes:
     - "./cores:/var/solr"
    ports:
     - "8913:8983"

