version: '3.2'

services:

# -----------------------------------------------------------
# Automated test engine - tests the website from 'outside'
#
# Based on https://github.com/SeleniumHQ/docker-selenium/tree/3.141.59-zirconium#version-3-with-swarm-support
# -----------------------------------------------------------

  robot:
    image: ukwa/robot-framework:latest
    environment: 
      - "HOST=${HOST}"
      - "PUSH_GATEWAY=${PUSH_GATEWAY}"
      - "PROMETHEUS_JOB_NAME=${PROMETHEUS_JOB_NAME}"
    volumes:
      - ./make_profile.py:/make_profile.py
      - ./tests:/tests:ro
      - ./results:/results:rw
    depends_on:
      - hub
    deploy:
      restart_policy:
        # Run once:
        condition: on-failure
        # If it fails, run every hour:
        delay: 60m

  firefox:
    image: selenium/node-firefox:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
      - "no_proxy=hub"
      - "HUB_HOST=hub"
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
      - "no_proxy=hub"
      - "HUB_HOST=hub"
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  hub:
    image: selenium/hub:3.141.59-zinc
    ports:
      - "4444:4444"
    depends_on:
      - firefox
      - chrome

