version: '3.2'

services:

# -----------------------------------------------------------
# Automated test engine - tests the website from 'outside'
#
# Based on https://github.com/SeleniumHQ/docker-selenium/tree/3.141.59-zirconium#version-3-with-swarm-support
# -----------------------------------------------------------

  robot:
    image: ukwa/robot-framework:1.2.0
    environment: 
      - "HOST=${HOST}"
      - "PUSH_GATEWAY=${PUSH_GATEWAY}"
      - "PROMETHEUS_JOB_NAME=${PROMETHEUS_JOB_NAME}"
      - "HTTPS_PROXY=${HTTPS_PROXY}"
    volumes:
      - ./results:/results:rw
    deploy:
      restart_policy:
        # Run once:
        condition: on-failure
        # If it fails, run every hour:
        delay: 60m


