apiVersion: 1

deleteDatasources:
- name: "Frequent  Crawler Logs"
  orgId: 1

datasources:
- name: "Frequent  Crawler Logs"
  type: elasticsearch
  access: proxy
  url: http://logs.wa.bl.uk:9200
  database: "[crawl_log-]YYYY.MM.DD"
  isDefault: true
  jsonData:
    interval: "Daily"
    esVersion: "7.16.1"
    timeField: "crawled.timestamp"
