# https://grafana.com/docs/grafana/latest/datasources/postgres/#configure-the-data-source-with-provisioning
apiVersion: 1

datasources:
  - name: "W3ACT DB"
    type: postgres
    url: postgres:5432
    database: w3act
    # Using a read-only 'viewer' DB role:
    user: viewer
    secureJsonData:
      # https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables
      password: ${W3ACT_PSQL_VIEWER_PASSWORD}
    jsonData:
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 906 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false