version: '3.7'

services:
  rclone:
    image: rclone/rclone
    #command: "rcd --rc-web-gui --rc-addr=:5572 --rc-enable-metrics --rc-web-gui-no-open-browser --rc-user=ingest --rc-pass=ingest"
    command: 'copy --max-age 48h --no-traverse /mnt/gluster/fc/heritrix/output/frequent-npld hadoop3:/heritrix/output/frequent-npld --include "*.warc.gz" --include "crawl.log.cp*"'
    environment:
      - "HTTPS_PROXY=http://explorer.bl.uk:3127"
    user: "1002:1002"
    ports:
      - "5572:5572"
    volumes:
      - "./config:/config/rclone"
      - "./cache:/home/ingest/.cache"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "/mnt/gluster:/mnt/gluster"
