version: '3.2'

services:

  # NGINX to pull all services together:
  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9000:80"

  # PyWB for QA
  pywb:
    image: ukwa/ukwa-pywb:2.5.x-beta
    environment:
      UKWA_INDEX: "http://cdx.api.wa.bl.uk/data-heritrix?url={url}&closest={closest}&sort=closest&filter=!statuscode:429&filter=!mimetype:warc/revisit"
      UKWA_ARCHIVE: "webhdfs://hdfs.api.wa.bl.uk"
      WEBHDFS_USER: "access"
    ports:
      - "7070:8080"
    volumes:
      - ./config/pywb.yaml:/webarchive/config.yaml

  # PDF to HTML service
  pdf2htmlex:
    image: ukwa/pdf2htmlex:1.0.1
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2G'
    depends_on:
      - pywb

  # W3ACT
  w3act:
    image: ukwa/w3act:latest
    command: /w3act/bin/w3act -J-Xmx6g -J-XX:+ExitOnOutOfMemoryError -Dconfig.file=/w3act/conf/docker.conf -Dpidfile.path=/dev/null -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1898 -Dcom.sun.management.jmxremote.rmi.port=1898 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=${JMX_HOSTNAME}
    environment:
      - "APPLICATION_NAVBAR_COLOR=${APPLICATION_NAVBAR_COLOR}"
      - "APPLICATION_SECRET=${APPLICATION_SECRET}"
      - "SECRET_SERVER_USER=${SECRET_SERVER_USER}"
      - "SECRET_SERVER_PASSWORD=${SECRET_SERVER_PASSWORD}"
      - "DB_DRIVER=org.postgresql.Driver"
      - "DB_URI=postgres://w3act:${W3ACT_PSQL_PASSWORD}@postgres/w3act"
      - "USE_TEST_DATA=false"
      - "ENABLE_DDHAPT=true"
      - "SMTP_SERVER=juno.bl.uk"
      - "WAYBACK_URL=http://pywb:8080/archive/" # Used by PDF2HTML proxy
      - "CDXSERVER_ENDPOINT=http://cdx.api.wa.bl.uk/data-heritrix"
      - "MONITRIX_URI=http://monitrix:5601/app/kibana"
      - "PDFTOHTMLEX_URI=http://pdf2htmlex:5000/convert?url="
      - "AMQP_HOST=amqp"
      - "SERVER_NAME=${W3ACT_SERVER_NAME}"
      - "PII_URI=${PII_URL}"
      - "ACCESS_RESOLVER_URI=${W3ACT_SERVER_NAME}/access/resolve/"
      - "ENABLE_EVOLUTIONS=true"
      - "APPLY_EVOLUTIONS=true" # This is generally safe to enable, but should only be done when migrations are expected.
      - "APPLY_DOWN_EVOLUTIONS=false" # WARNING DOWNS ARE POTENTIALLY DESTRUCTIVE
    volumes:
      - "${DDHAPT_SIPS_SUBMITTED_DIR}:/opt/data/dls_sips_copy"
      - "${DDHAPT_EBOOKS_SUBMISSION_DIR}:/opt/data/w3act/ebooks:shared"
      - "${DDHAPT_EJOURNALS_SUBMISSION_DIR}:/opt/data/w3act/ejournals:shared"
    ports:
      - "9001:9000"
      - "1898:1898"
    depends_on:
      - pywb
      - pdf2htmlex

  # PostgreSQL
  postgres:
    image: postgres:9.6.2
    environment:
      - "POSTGRES_USER=w3act"
      - "POSTGRES_PASSWORD=${W3ACT_PSQL_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${W3ACT_PSQL_DIR}:/var/lib/postgresql/data"
      - "${W3ACT_DUMPS_DIR}:/tmp"

  # -------------------------------------------------------------
  # Crawl log viewer
  # -------------------------------------------------------------
  crawl-log-viewer:
    image: ukwa/crawl-log-viewer
    environment:
      - "SCRIPT_NAME=/act/logs"
    volumes:
      - ./config/crawl-log-viewer-topics.json:/usr/src/app/topics.json

  # -------------------------------------------------------------
  # Notebooks and Dashboards
  # -------------------------------------------------------------
  nbapps:
    image: ukwa/ukwa-notebook-apps
    command: "--base_url=/act/nbapps/ --no-browser --template=lab --debug /app"
    environment:
     - "HTTPS_PROXY=https://explorer.bl.uk:3127" # This is needed because we're talking to the live public API (we should have an internal one)
     - "PYTHONPATH=/app"

  metabase:
    image: metabase/metabase:latest
    ports:
      - 3001:3000

networks:
  # Make network attachable so tasks can be run:
  default:
    driver: overlay
    attachable: true

