version: "3.2"

services:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9000:8080
    environment:
      - "KAFKA_CLUSTERS_0_NAME=fc-kafka"
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092"
      - "DYNAMIC_CONFIG_ENABLED=true"
      - "LOGGING_LEVEL_ROOT=info"
    networks:
      - kafka

networks:
  kafka:
    external:
      name: fc_kafka_default

