version: "3.2"

services:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9000:8080
    environment:
      - "KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092"
      - "DYNAMIC_CONFIG_ENABLED=true"
    networks:
      - kafka

networks:
  kafka:
    external:
      name: fc_kafka_default

