version: "3.2"

services:

  # ----------------------------------------------
  # QA Access
  # ----------------------------------------------
  warc-server:
    image: ukwa/warc-server
    ports:
      - 8001:8000
    environment:
      - "WARC_PATHS=/heritrix/output,/heritrix/wren"
        #      - "TRACKDB_URL=http://solr8.api.wa.bl.uk/solr/tracking"
      - "TRACKDB_URL=''"
    volumes:
      - "${HERITRIX_OUTPUT_PATH}:/heritrix/output"
      - "${HERITRIX_WREN_PATH}:/heritrix/wren"
#    # To resolve solr8.api.wa.bl.uk
#    dns:
#      - 194.66.236.150
#      - 194.66.236.163

  # OpenWayback for QA
  openwayback:
    image: ukwa/waybacks
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - "UKWA_OWB_VERSION=qa"
      - "WAYBACK_URL_PORT=8080"
      - "WAYBACK_PROXY_PORT=8090"
      - "CDX_WHITELIST="
      - "WAYBACK_EXCLUDE_FILE=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/exclude.txt"
      - "WAYBACK_EMBARGO=0"
      - "WAYBACK_HTTPFS_PREFIX=http://warc-server:8000/by-filename/"
      - "CDX_INDEX_SERVER=${CDXSERVER_ENDPOINT}"
      - "WAYBACK_URL_PREFIX=http://${WB_HOST}:8080"
      - "WAYBACK_URL_HOST=${WB_HOST}"

  # PyWB for QA
  pywb:
    image: ukwa/ukwa-pywb:2.5.x-beta
    environment:
      UKWA_INDEX: "cdx+${CDXSERVER_ENDPOINT}"
      UKWA_ARCHIVE: "webhdfs://warc-server:8000/by-filename/"
      WEBHDFS_USER: "access"
    ports:
      - "7070:8080"
    volumes:
      - ./pywb-config.yaml:/webarchive/config.yaml


