
# This is the base configuration. 
version: '3.2'

services:

  # -------------------------------------------------------------
  # The Python service that provides some basic APIs
  # -------------------------------------------------------------
  ukwa-access-api:
    image: ukwa/ukwa-access-api
    environment:
      - "CDX_SERVER=http://cdx.api.wa.bl.uk/data-heritrix"
      - "WEBHDFS_PREFIX=http://192.168.45.13:14000/webhdfs/v1"
      - "KAFKA_BOOTSTRAP_SERVERS=192.168.45.15:9094"
      - "KAFKA_CRAWLED_TOPIC=fc.crawled"
      - "KAFKA_SEEK_TO_BEGINNING=False"
      - "API_LABEL=ACCESS API PROTOTYPE"
      - "KAFKA_LAUNCH_BROKER=192.168.45.15:9094"
      - "KAFKA_LAUNCH_TOPIC=fc.tocrawl.npld"
      - "HTTPS_PROXY=http://194.66.232.92:3127/"
      - "SERVER_NAME=beta.webarchive.org.uk"
      - "ANALYSIS_SOURCE_FILE=/analysis/fc.crawled.json"
    ports:
     - "8000:8000"
    volumes:
      - analysis-volume:/analysis

  # Analyses recent crawl behaviour by processing the crawled data stream:
  analyse:
    image: ukwa/crawl-streams
    command: "analyse -k 192.168.45.15:9094 -u 2 -o /analysis/fc.crawled.json"
    volumes:
      - analysis-volume:/analysis

  # An embedded, bannerless OA Wayback to render:
  pywb-nobanner:
    image: ukwa/ukwa-pywb:latest
    ports:
      - "8090:8080"
    environment:
      - "WEBHDFS_USER=access"
      - "UKWA_INDEX=xmlquery+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://192.168.45.13:14000"
    volumes:
      - ./pywb/config-nobanner.yaml:/webarchive/config.yaml
      - /root/wayback-config/acl/:/ukwa_pywb/acl/
      - ./pywb/empty-banner.js:/ukwa_pywb/static/default_banner.js
    networks:
      - default
      - attach

  # Web page rendering post-crawl:
  webrender:
    image: ukwa/webrender-api:1.0.10
    environment:
      - "HTTP_PROXY=http://pywb-nobanner:8080"
      - "DOCKER_NETWORK=access_attach"
      - "LC_ALL=en_US.utf8"
      - "WEB_RENDER_TMP=/tmp/webrender"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/webrender:/tmp/webrender
    deploy:
      replicas: 1
    ports:
     - "8010:8010"


  # -------------------------------------------------------------
  # OA Wayback configuration:
  # -------------------------------------------------------------
  pywb:
    image: ukwa/ukwa-pywb:2.4.0-beta-5
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - "DEBUG=True"
      - "WEBHDFS_USER=access"
      - "UKWA_INDEX=xmlquery+http://cdx.api.wa.bl.uk/data-heritrix"
      - "UKWA_ARCHIVE=webhdfs://192.168.45.13:14000"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logs.wa.bl.uk:12201"
    volumes:
      - ./pywb/config.yaml:/webarchive/config.yaml
      - /root/wayback-config/acl/:/ukwa_pywb/acl/


  # -------------------------------------------------------------
  # The main UKWA UI itself
  # -------------------------------------------------------------
  ukwa-ui:
    image: ukwa/ukwa-ui:latest
    command: java -Djava.security.egd=file:/dev/./urandom -jar /ukwa-ui.war --spring.config.location=file:/application.properties
    ports:
     - "8080:8080"
    environment:
     - "SET_PROTOCOL_TO_HTTPS=true"
     - "OFF_SITE_URL=https://beta.webarchive.org.uk/wayback/archive/"
     - "SOLR_COLLECTION_SEARCH_PATH=http://ukwa_collections:8983"
     - "SOLR_COLLECTION_SEARCH_REQUEST_HANDLER=/solr/collections/select"
     - "SOLR_FULL_TEXT_SEARCH_PATH=http://192.168.45.33:8983"
     - "SOLR_FULL_TEXT_SEARCH_REQUEST_HANDLER=/solr/all/select"
     - "SOLR_READ_TIMEOUT=600000"
     - "SOLR_CONNECTION_TIMEOUT=60000"
     - "SOLR_USERNAME="
     - "SOLR_PASSWORD="
     - "SOLR_SHOW_STUB_DATA_SERVICE_NOT_AVAILABLE=true"
     - "BL_SMTP_SERVER_HOST=juno.bl.uk"
     - "BL_SMTP_USERNAME="
     - "BL_SMTP_PASSWORD="
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logs.wa.bl.uk:12201"
    volumes:
      - ./ukwa-ui/ukwa-ui.properties:/application.properties:ro   

  # Collections index for Topics & Themes of the UKWA UI
  ukwa_collections:
    image: solr:6.3
    volumes:
    # n.b container solr userid (8983) should have write permission on host solr dir
       - "/data/solr/ukwa_collections/server:/opt/solr/server" 
    ports:
       - "9020:8983"

  # -------------------------------------------------------------
  # Mementos
  # -------------------------------------------------------------
  mementos:
    image: ukwa/mementoweb-webclient
    command: "/mementos/bin/mementos-webclient -Dhttp.proxyHost=194.66.232.92 -Dhttp.proxyPort=3127 -Dconfig.file=/mementos/conf/application.conf -Dpidfile.path=/dev/null"
    ports:
      - "9000:9000"
    environment:
      - "JAVA_OPTS=-Xmx1g -Dhttp.proxyHost=explorer -Dhttp.proxyPort=3127"

  # Rate limiter for Mementos:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logs.wa.bl.uk:12201"
    volumes:
      - ./mementos/nginx.conf:/etc/nginx/conf.d/default.conf:ro   

  # -------------------------------------------------------------
  # Shine service and database
  # -------------------------------------------------------------

  # Shine
  shine:
   image: ukwa/shine
   ports:
     - "9001:9000"
   environment:
     - "SOLR_URL=http://192.168.45.70:8983/solr/jisc"
     - "JAVA_OPTS=-Xmx2g -XX:+ExitOnOutOfMemoryError"
   depends_on:
     - shinedb

  # Shine state    
  shinedb:
    image: postgres:9.6.2
    volumes:
      - "/data/shine/postgresql/data:/var/lib/postgresql/data"   
      
      
volumes:
  analysis-volume:

networks:
  default:
    driver: overlay
    attachable: true
  attach:
    driver: overlay
    attachable: true
