version: '2'

services:

  dbmate:
    image: amacneil/dbmate
    command: up
    environment:
      - "DATABASE_URL=postgres://ddhapt:ddhapt@${DDHAPT_DB_HOST}:5435/ddhapt?sslmode=disable"
    volumes:
      - ./db:/db
    restart: never
