name: Deploy UKWA BETA Services

on:
  push:
    branches:
      - master

jobs:
  test-job:
    runs-on: [self-hosted, linux, x64, ukwa-beta-swarm]
    steps:
    - name: Run test for env vars
      run: export
      shell: bash
    - name: Run test for files
      run: ls
      shell: bash

