name: Deploy UKWA BETA Services

on:
  push:
    branches:
      # Switching this off as no runners at present
      - this-branch-does-not-exist

jobs:
  test-job:
    runs-on: [self-hosted, linux, x64, ukwa-services-beta-swarm]
    steps:
    - name: Run test for env vars
      run: export
      shell: bash
    - name: Run test for files
      run: ls $HOME
      shell: bash

