name: Deploy UKWA BETA Services

# Switching this off as no runners at present
#on:
#  push:
#    branches:
#      - master

jobs:
  test-job:
    runs-on: [self-hosted, linux, x64, ukwa-services-beta-swarm]
    steps:
    - name: Run test for env vars
      run: export
      shell: bash
    - name: Run test for files
      run: ls $HOME
      shell: bash

